// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.flutter.plugins.googlesignin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(exception.code, exception.message, exception.details)
  } else {
    listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception))
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null
) : Throwable()

/** Pigeon version of SignInOption. */
enum class SignInType(val raw: Int) {
  /** Default configuration. */
  STANDARD(0),
  /** Recommended configuration for game sign in. */
  GAMES(1);

  companion object {
    fun ofRaw(raw: Int): SignInType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class GetCredentialFailureType(val raw: Int) {
  /** Indicates that a credential was returned, but it was not of the expected type. */
  UNEXPECTED_CREDENTIAL_TYPE(0),
  /** Indicates that a server client ID was not provided. */
  MISSING_SERVER_CLIENT_ID(1),
  /** The request was internally interrupted. */
  INTERRUPTED(2),
  /** The request was canceled by the user. */
  CANCELED(3),
  /** No matching credential was found. */
  NO_CREDENTIAL(4),
  /** The provider was not properly configured. */
  PROVIDER_CONFIGURATION_ISSUE(5),
  /** The credential manager is not supported on this device. */
  UNSUPPORTED(6),
  /** The request failed for an unknown reason. */
  UNKNOWN(7);

  companion object {
    fun ofRaw(raw: Int): GetCredentialFailureType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AuthorizeFailureType(val raw: Int) {
  /**
   * Indicates that the requested types are not currently authorized.
   *
   * This is returned only if promptIfUnauthorized is false, indicating that the user would need to
   * be prompted for authorization.
   */
  UNAUTHORIZED(0),
  /** Indicates that the call to AuthorizationClient.authorize itself failed. */
  AUTHORIZE_FAILURE(1),
  /**
   * Corresponds to SendIntentException, indicating that the pending intent is no longer available.
   */
  PENDING_INTENT_EXCEPTION(2),
  /**
   * Corresponds to an SendIntentException in onActivityResult, indicating that either authorization
   * failed, or the result was not available for some reason.
   */
  API_EXCEPTION(3),
  /**
   * Indicates that the user needs to be prompted for authorization, but there is no current
   * activity to prompt in.
   */
  NO_ACTIVITY(4);

  companion object {
    fun ofRaw(raw: Int): AuthorizeFailureType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Pigeon version of SignInInitParams.
 *
 * See SignInInitParams for details.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitParams(
    val scopes: List<String>,
    val signInType: SignInType,
    val hostedDomain: String? = null,
    val clientId: String? = null,
    val serverClientId: String? = null,
    val forceCodeForRefreshToken: Boolean
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitParams {
      val scopes = pigeonVar_list[0] as List<String>
      val signInType = pigeonVar_list[1] as SignInType
      val hostedDomain = pigeonVar_list[2] as String?
      val clientId = pigeonVar_list[3] as String?
      val serverClientId = pigeonVar_list[4] as String?
      val forceCodeForRefreshToken = pigeonVar_list[5] as Boolean
      return InitParams(
          scopes, signInType, hostedDomain, clientId, serverClientId, forceCodeForRefreshToken)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        scopes,
        signInType,
        hostedDomain,
        clientId,
        serverClientId,
        forceCodeForRefreshToken,
    )
  }
}

/**
 * Pigeon version of GoogleSignInUserData.
 *
 * See GoogleSignInUserData for details.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UserData(
    val displayName: String? = null,
    val email: String,
    val id: String,
    val photoUrl: String? = null,
    val idToken: String? = null,
    val serverAuthCode: String? = null
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserData {
      val displayName = pigeonVar_list[0] as String?
      val email = pigeonVar_list[1] as String
      val id = pigeonVar_list[2] as String
      val photoUrl = pigeonVar_list[3] as String?
      val idToken = pigeonVar_list[4] as String?
      val serverAuthCode = pigeonVar_list[5] as String?
      return UserData(displayName, email, id, photoUrl, idToken, serverAuthCode)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        displayName,
        email,
        id,
        photoUrl,
        idToken,
        serverAuthCode,
    )
  }
}

/**
 * The information necessary to build a an authorization request.
 *
 * Corresponds to the native AuthorizationRequest object, but only contains the fields used by this
 * plugin.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformAuthorizationRequest(val scopes: List<String>) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformAuthorizationRequest {
      val scopes = pigeonVar_list[0] as List<String>
      return PlatformAuthorizationRequest(scopes)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        scopes,
    )
  }
}

/**
 * The information necessary to build a credential request.
 *
 * Combines the parts of the native GetCredentialRequest and CredentialOption classes that are used
 * for this plugin.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GetCredentialRequestParams(
    val filterToAuthorized: Boolean,
    val autoSelectEnabled: Boolean,
    val serverClientId: String? = null
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetCredentialRequestParams {
      val filterToAuthorized = pigeonVar_list[0] as Boolean
      val autoSelectEnabled = pigeonVar_list[1] as Boolean
      val serverClientId = pigeonVar_list[2] as String?
      return GetCredentialRequestParams(filterToAuthorized, autoSelectEnabled, serverClientId)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        filterToAuthorized,
        autoSelectEnabled,
        serverClientId,
    )
  }
}

/**
 * Pigeon equivalent of the native GoogleIdTokenCredential.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformGoogleIdTokenCredential(
    val displayName: String? = null,
    val familyName: String? = null,
    val givenName: String? = null,
    val id: String,
    val idToken: String,
    val profilePictureUri: String? = null
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformGoogleIdTokenCredential {
      val displayName = pigeonVar_list[0] as String?
      val familyName = pigeonVar_list[1] as String?
      val givenName = pigeonVar_list[2] as String?
      val id = pigeonVar_list[3] as String
      val idToken = pigeonVar_list[4] as String
      val profilePictureUri = pigeonVar_list[5] as String?
      return PlatformGoogleIdTokenCredential(
          displayName, familyName, givenName, id, idToken, profilePictureUri)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        displayName,
        familyName,
        givenName,
        id,
        idToken,
        profilePictureUri,
    )
  }
}

/**
 * The response from a `getCredential` call.
 *
 * This is not the same as a native GetCredentialResponse since modeling the response type hierarchy
 * and two-part callback in this interface layer would add a lot of complexity that is not needed
 * for the plugin's use case. It is instead a processed version of the results of those callbacks.
 *
 * Generated class from Pigeon that represents data sent in messages. This class should not be
 * extended by any user class outside of the generated file.
 */
sealed class GetCredentialResult
/**
 * An authentication failure.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GetCredentialFailure(
    /** The type of failure. */
    val type: GetCredentialFailureType,
    /** The message associated with the failure, if any. */
    val message: String? = null
) : GetCredentialResult() {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetCredentialFailure {
      val type = pigeonVar_list[0] as GetCredentialFailureType
      val message = pigeonVar_list[1] as String?
      return GetCredentialFailure(type, message)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        type,
        message,
    )
  }
}

/**
 * A successful authentication result.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GetCredentialSuccess(val credential: PlatformGoogleIdTokenCredential) :
    GetCredentialResult() {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetCredentialSuccess {
      val credential = pigeonVar_list[0] as PlatformGoogleIdTokenCredential
      return GetCredentialSuccess(credential)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        credential,
    )
  }
}

/**
 * The response from an `authorize` call.
 *
 * Generated class from Pigeon that represents data sent in messages. This class should not be
 * extended by any user class outside of the generated file.
 */
sealed class AuthorizeResult
/**
 * An authorization failure
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthorizeFailure(
    /** The type of failure. */
    val type: AuthorizeFailureType,
    /** The message associated with the failure, if any. */
    val message: String? = null
) : AuthorizeResult() {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthorizeFailure {
      val type = pigeonVar_list[0] as AuthorizeFailureType
      val message = pigeonVar_list[1] as String?
      return AuthorizeFailure(type, message)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        type,
        message,
    )
  }
}

/**
 * A successful authorization result.
 *
 * Corresponds to a native AuthorizationResult.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformAuthorizationResult(
    val accessToken: String? = null,
    val serverAuthCode: String? = null,
    val grantedScopes: List<String>
) : AuthorizeResult() {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformAuthorizationResult {
      val accessToken = pigeonVar_list[0] as String?
      val serverAuthCode = pigeonVar_list[1] as String?
      val grantedScopes = pigeonVar_list[2] as List<String>
      return PlatformAuthorizationResult(accessToken, serverAuthCode, grantedScopes)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        accessToken,
        serverAuthCode,
        grantedScopes,
    )
  }
}

private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let { SignInType.ofRaw(it.toInt()) }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let { GetCredentialFailureType.ofRaw(it.toInt()) }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let { AuthorizeFailureType.ofRaw(it.toInt()) }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { InitParams.fromList(it) }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { UserData.fromList(it) }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { PlatformAuthorizationRequest.fromList(it) }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { GetCredentialRequestParams.fromList(it) }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformGoogleIdTokenCredential.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { GetCredentialFailure.fromList(it) }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { GetCredentialSuccess.fromList(it) }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { AuthorizeFailure.fromList(it) }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { PlatformAuthorizationResult.fromList(it) }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is SignInType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is GetCredentialFailureType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is AuthorizeFailureType -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is InitParams -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is UserData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PlatformAuthorizationRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is GetCredentialRequestParams -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PlatformGoogleIdTokenCredential -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is GetCredentialFailure -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is GetCredentialSuccess -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is AuthorizeFailure -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PlatformAuthorizationResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GoogleSignInApi {
  /** Initializes a sign in request with the given parameters. */
  fun init(params: InitParams)
  /** Starts a silent sign in. */
  fun signInSilently(callback: (Result<UserData>) -> Unit)
  /** Starts a sign in with user interaction. */
  fun signIn(callback: (Result<UserData>) -> Unit)
  /** Requests the access token for the current sign in. */
  fun getAccessToken(email: String, shouldRecoverAuth: Boolean, callback: (Result<String>) -> Unit)
  /** Signs out the current user. */
  fun signOut(callback: (Result<Unit>) -> Unit)
  /** Revokes scope grants to the application. */
  fun disconnect(callback: (Result<Unit>) -> Unit)
  /** Returns whether the user is currently signed in. */
  fun isSignedIn(): Boolean
  /** Clears the authentication caching for the given token, requiring a new sign in. */
  fun clearAuthCache(token: String)
  /** Requests access to the given scopes. */
  fun requestScopes(scopes: List<String>, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by GoogleSignInApi. */
    val codec: MessageCodec<Any?> by lazy { MessagesPigeonCodec() }
    /**
     * Sets up an instance of `GoogleSignInApi` to handle messages through the `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
        binaryMessenger: BinaryMessenger,
        api: GoogleSignInApi?,
        messageChannelSuffix: String = ""
    ) {
      val separatedMessageChannelSuffix =
          if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.init$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as InitParams
            val wrapped: List<Any?> =
                try {
                  api.init(paramsArg)
                  listOf(null)
                } catch (exception: Throwable) {
                  wrapError(exception)
                }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.signInSilently$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.signInSilently { result: Result<UserData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.signIn$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.signIn { result: Result<UserData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.getAccessToken$separatedMessageChannelSuffix",
                codec,
                taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val emailArg = args[0] as String
            val shouldRecoverAuthArg = args[1] as Boolean
            api.getAccessToken(emailArg, shouldRecoverAuthArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.signOut$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.signOut { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.disconnect$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disconnect { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.isSignedIn$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> =
                try {
                  listOf(api.isSignedIn())
                } catch (exception: Throwable) {
                  wrapError(exception)
                }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.clearAuthCache$separatedMessageChannelSuffix",
                codec,
                taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            val wrapped: List<Any?> =
                try {
                  api.clearAuthCache(tokenArg)
                  listOf(null)
                } catch (exception: Throwable) {
                  wrapError(exception)
                }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.GoogleSignInApi.requestScopes$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val scopesArg = args[0] as List<String>
            api.requestScopes(scopesArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CredentialManagerApi {
  fun getCredential(
      params: GetCredentialRequestParams,
      callback: (Result<GetCredentialResult>) -> Unit
  )

  fun clearCredentialState(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by CredentialManagerApi. */
    val codec: MessageCodec<Any?> by lazy { MessagesPigeonCodec() }
    /**
     * Sets up an instance of `CredentialManagerApi` to handle messages through the
     * `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
        binaryMessenger: BinaryMessenger,
        api: CredentialManagerApi?,
        messageChannelSuffix: String = ""
    ) {
      val separatedMessageChannelSuffix =
          if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.CredentialManagerApi.getCredential$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as GetCredentialRequestParams
            api.getCredential(paramsArg) { result: Result<GetCredentialResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.CredentialManagerApi.clearCredentialState$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearCredentialState { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AuthorizationClientApi {
  fun authorize(
      params: PlatformAuthorizationRequest,
      promptIfUnauthorized: Boolean,
      callback: (Result<AuthorizeResult>) -> Unit
  )

  companion object {
    /** The codec used by AuthorizationClientApi. */
    val codec: MessageCodec<Any?> by lazy { MessagesPigeonCodec() }
    /**
     * Sets up an instance of `AuthorizationClientApi` to handle messages through the
     * `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
        binaryMessenger: BinaryMessenger,
        api: AuthorizationClientApi?,
        messageChannelSuffix: String = ""
    ) {
      val separatedMessageChannelSuffix =
          if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.google_sign_in_android.AuthorizationClientApi.authorize$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as PlatformAuthorizationRequest
            val promptIfUnauthorizedArg = args[1] as Boolean
            api.authorize(paramsArg, promptIfUnauthorizedArg) { result: Result<AuthorizeResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
