// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(ffi.Pointer<objc.ObjCBlockImpl>)
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl>
_NativeLibrary_wrapListenerBlock_1pl9qdv(ffi.Pointer<objc.ObjCBlockImpl> block);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Pointer<objc.ObjCBlockImpl>,
    ffi.Pointer<objc.ObjCBlockImpl>,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl>
_NativeLibrary_wrapBlockingBlock_1pl9qdv(
  ffi.Pointer<objc.ObjCBlockImpl> block,
  ffi.Pointer<objc.ObjCBlockImpl> listnerBlock,
  ffi.Pointer<objc.DOBJC_Context> context,
);

final class __CFDictionary extends ffi.Opaque {}

final class CGAffineTransform extends ffi.Struct {
  @ffi.Double()
  external double a;

  @ffi.Double()
  external double b;

  @ffi.Double()
  external double c;

  @ffi.Double()
  external double d;

  @ffi.Double()
  external double tx;

  @ffi.Double()
  external double ty;
}

enum NSSearchPathDirectory {
  NSApplicationDirectory(1),
  NSDemoApplicationDirectory(2),
  NSDeveloperApplicationDirectory(3),
  NSAdminApplicationDirectory(4),
  NSLibraryDirectory(5),
  NSDeveloperDirectory(6),
  NSUserDirectory(7),
  NSDocumentationDirectory(8),
  NSDocumentDirectory(9),
  NSCoreServiceDirectory(10),
  NSAutosavedInformationDirectory(11),
  NSDesktopDirectory(12),
  NSCachesDirectory(13),
  NSApplicationSupportDirectory(14),
  NSDownloadsDirectory(15),
  NSInputMethodsDirectory(16),
  NSMoviesDirectory(17),
  NSMusicDirectory(18),
  NSPicturesDirectory(19),
  NSPrinterDescriptionDirectory(20),
  NSSharedPublicDirectory(21),
  NSPreferencePanesDirectory(22),
  NSApplicationScriptsDirectory(23),
  NSItemReplacementDirectory(99),
  NSAllApplicationsDirectory(100),
  NSAllLibrariesDirectory(101),
  NSTrashDirectory(102);

  final int value;
  const NSSearchPathDirectory(this.value);

  static NSSearchPathDirectory fromValue(int value) => switch (value) {
    1 => NSApplicationDirectory,
    2 => NSDemoApplicationDirectory,
    3 => NSDeveloperApplicationDirectory,
    4 => NSAdminApplicationDirectory,
    5 => NSLibraryDirectory,
    6 => NSDeveloperDirectory,
    7 => NSUserDirectory,
    8 => NSDocumentationDirectory,
    9 => NSDocumentDirectory,
    10 => NSCoreServiceDirectory,
    11 => NSAutosavedInformationDirectory,
    12 => NSDesktopDirectory,
    13 => NSCachesDirectory,
    14 => NSApplicationSupportDirectory,
    15 => NSDownloadsDirectory,
    16 => NSInputMethodsDirectory,
    17 => NSMoviesDirectory,
    18 => NSMusicDirectory,
    19 => NSPicturesDirectory,
    20 => NSPrinterDescriptionDirectory,
    21 => NSSharedPublicDirectory,
    22 => NSPreferencePanesDirectory,
    23 => NSApplicationScriptsDirectory,
    99 => NSItemReplacementDirectory,
    100 => NSAllApplicationsDirectory,
    101 => NSAllLibrariesDirectory,
    102 => NSTrashDirectory,
    _ => throw ArgumentError('Unknown value for NSSearchPathDirectory: $value'),
  };
}

sealed class NSSearchPathDomainMask {
  static const NSUserDomainMask = 1;
  static const NSLocalDomainMask = 2;
  static const NSNetworkDomainMask = 4;
  static const NSSystemDomainMask = 8;
  static const NSAllDomainsMask = 65535;
}

sealed class NSVolumeEnumerationOptions {
  static const NSVolumeEnumerationSkipHiddenVolumes = 2;
  static const NSVolumeEnumerationProduceFileReferenceURLs = 4;
}

sealed class NSDirectoryEnumerationOptions {
  static const NSDirectoryEnumerationSkipsSubdirectoryDescendants = 1;
  static const NSDirectoryEnumerationSkipsPackageDescendants = 2;
  static const NSDirectoryEnumerationSkipsHiddenFiles = 4;
  static const NSDirectoryEnumerationIncludesDirectoriesPostOrder = 8;
  static const NSDirectoryEnumerationProducesRelativePathURLs = 16;
}

sealed class NSFileManagerItemReplacementOptions {
  static const NSFileManagerItemReplacementUsingNewMetadataOnly = 1;
  static const NSFileManagerItemReplacementWithoutDeletingBackupItem = 2;
}

enum NSURLRelationship {
  NSURLRelationshipContains(0),
  NSURLRelationshipSame(1),
  NSURLRelationshipOther(2);

  final int value;
  const NSURLRelationship(this.value);

  static NSURLRelationship fromValue(int value) => switch (value) {
    0 => NSURLRelationshipContains,
    1 => NSURLRelationshipSame,
    2 => NSURLRelationshipOther,
    _ => throw ArgumentError('Unknown value for NSURLRelationship: $value'),
  };
}

sealed class NSFileManagerUnmountOptions {
  static const NSFileManagerUnmountAllPartitionsAndEjectDisk = 1;
  static const NSFileManagerUnmountWithoutUI = 2;
}

final class __IOSurface extends ffi.Opaque {}

enum AVKeyValueStatus {
  AVKeyValueStatusUnknown(0),
  AVKeyValueStatusLoading(1),
  AVKeyValueStatusLoaded(2),
  AVKeyValueStatusFailed(3),
  AVKeyValueStatusCancelled(4);

  final int value;
  const AVKeyValueStatus(this.value);

  static AVKeyValueStatus fromValue(int value) => switch (value) {
    0 => AVKeyValueStatusUnknown,
    1 => AVKeyValueStatusLoading,
    2 => AVKeyValueStatusLoaded,
    3 => AVKeyValueStatusFailed,
    4 => AVKeyValueStatusCancelled,
    _ => throw ArgumentError('Unknown value for AVKeyValueStatus: $value'),
  };
}

sealed class CMTimeFlags {
  static const kCMTimeFlags_Valid = 1;
  static const kCMTimeFlags_HasBeenRounded = 2;
  static const kCMTimeFlags_PositiveInfinity = 4;
  static const kCMTimeFlags_NegativeInfinity = 8;
  static const kCMTimeFlags_Indefinite = 16;
  static const kCMTimeFlags_ImpliedValueFlagsMask = 28;
}

@ffi.Packed(4)
final class CMTime extends ffi.Struct {
  @ffi.Int64()
  external int value;

  @ffi.Int32()
  external int timescale;

  @ffi.Uint32()
  external int flags;

  @ffi.Int64()
  external int epoch;
}

final class CVSMPTETime extends ffi.Struct {
  @ffi.Short()
  external int subframes;

  @ffi.Short()
  external int subframeDivisor;

  @ffi.UnsignedInt()
  external int counter;

  @ffi.UnsignedInt()
  external int type;

  @ffi.UnsignedInt()
  external int flags;

  @ffi.Short()
  external int hours;

  @ffi.Short()
  external int minutes;

  @ffi.Short()
  external int seconds;

  @ffi.Short()
  external int frames;
}

final class CVTimeStamp extends ffi.Struct {
  @ffi.Uint32()
  external int version;

  @ffi.Int32()
  external int videoTimeScale;

  @ffi.Int64()
  external int videoTime;

  @ffi.Uint64()
  external int hostTime;

  @ffi.Double()
  external double rateScalar;

  @ffi.Int64()
  external int videoRefreshPeriod;

  external CVSMPTETime smpteTime;

  @ffi.Uint64()
  external int flags;

  @ffi.Uint64()
  external int reserved;
}

final class CGContext extends ffi.Opaque {}

final class CGColor extends ffi.Opaque {}

final class CGColorSpace extends ffi.Opaque {}

final class CGImage extends ffi.Opaque {}

final class CGPath extends ffi.Opaque {}

final class CGLayer extends ffi.Opaque {}

final class _CGLContextObject extends ffi.Opaque {}

final class _CGLPixelFormatObject extends ffi.Opaque {}

final class __CVBuffer extends ffi.Opaque {}

final class CGImageSource extends ffi.Opaque {}

enum CGImagePropertyOrientation {
  kCGImagePropertyOrientationUp(1),
  kCGImagePropertyOrientationUpMirrored(2),
  kCGImagePropertyOrientationDown(3),
  kCGImagePropertyOrientationDownMirrored(4),
  kCGImagePropertyOrientationLeftMirrored(5),
  kCGImagePropertyOrientationRight(6),
  kCGImagePropertyOrientationRightMirrored(7),
  kCGImagePropertyOrientationLeft(8);

  final int value;
  const CGImagePropertyOrientation(this.value);

  static CGImagePropertyOrientation fromValue(int value) => switch (value) {
    1 => kCGImagePropertyOrientationUp,
    2 => kCGImagePropertyOrientationUpMirrored,
    3 => kCGImagePropertyOrientationDown,
    4 => kCGImagePropertyOrientationDownMirrored,
    5 => kCGImagePropertyOrientationLeftMirrored,
    6 => kCGImagePropertyOrientationRight,
    7 => kCGImagePropertyOrientationRightMirrored,
    8 => kCGImagePropertyOrientationLeft,
    _ => throw ArgumentError(
      'Unknown value for CGImagePropertyOrientation: $value',
    ),
  };
}

sealed class IOSurfaceLockOptions {
  static const kIOSurfaceLockReadOnly = 1;
  static const kIOSurfaceLockAvoidSync = 2;
}

sealed class IOSurfacePurgeabilityState {
  static const kIOSurfacePurgeableNonVolatile = 0;
  static const kIOSurfacePurgeableVolatile = 1;
  static const kIOSurfacePurgeableEmpty = 2;
  static const kIOSurfacePurgeableKeepCurrent = 3;
}

enum MTLPixelFormat {
  MTLPixelFormatInvalid(0),
  MTLPixelFormatA8Unorm(1),
  MTLPixelFormatR8Unorm(10),
  MTLPixelFormatR8Unorm_sRGB(11),
  MTLPixelFormatR8Snorm(12),
  MTLPixelFormatR8Uint(13),
  MTLPixelFormatR8Sint(14),
  MTLPixelFormatR16Unorm(20),
  MTLPixelFormatR16Snorm(22),
  MTLPixelFormatR16Uint(23),
  MTLPixelFormatR16Sint(24),
  MTLPixelFormatR16Float(25),
  MTLPixelFormatRG8Unorm(30),
  MTLPixelFormatRG8Unorm_sRGB(31),
  MTLPixelFormatRG8Snorm(32),
  MTLPixelFormatRG8Uint(33),
  MTLPixelFormatRG8Sint(34),
  MTLPixelFormatB5G6R5Unorm(40),
  MTLPixelFormatA1BGR5Unorm(41),
  MTLPixelFormatABGR4Unorm(42),
  MTLPixelFormatBGR5A1Unorm(43),
  MTLPixelFormatR32Uint(53),
  MTLPixelFormatR32Sint(54),
  MTLPixelFormatR32Float(55),
  MTLPixelFormatRG16Unorm(60),
  MTLPixelFormatRG16Snorm(62),
  MTLPixelFormatRG16Uint(63),
  MTLPixelFormatRG16Sint(64),
  MTLPixelFormatRG16Float(65),
  MTLPixelFormatRGBA8Unorm(70),
  MTLPixelFormatRGBA8Unorm_sRGB(71),
  MTLPixelFormatRGBA8Snorm(72),
  MTLPixelFormatRGBA8Uint(73),
  MTLPixelFormatRGBA8Sint(74),
  MTLPixelFormatBGRA8Unorm(80),
  MTLPixelFormatBGRA8Unorm_sRGB(81),
  MTLPixelFormatRGB10A2Unorm(90),
  MTLPixelFormatRGB10A2Uint(91),
  MTLPixelFormatRG11B10Float(92),
  MTLPixelFormatRGB9E5Float(93),
  MTLPixelFormatBGR10A2Unorm(94),
  MTLPixelFormatBGR10_XR(554),
  MTLPixelFormatBGR10_XR_sRGB(555),
  MTLPixelFormatRG32Uint(103),
  MTLPixelFormatRG32Sint(104),
  MTLPixelFormatRG32Float(105),
  MTLPixelFormatRGBA16Unorm(110),
  MTLPixelFormatRGBA16Snorm(112),
  MTLPixelFormatRGBA16Uint(113),
  MTLPixelFormatRGBA16Sint(114),
  MTLPixelFormatRGBA16Float(115),
  MTLPixelFormatBGRA10_XR(552),
  MTLPixelFormatBGRA10_XR_sRGB(553),
  MTLPixelFormatRGBA32Uint(123),
  MTLPixelFormatRGBA32Sint(124),
  MTLPixelFormatRGBA32Float(125),
  MTLPixelFormatBC1_RGBA(130),
  MTLPixelFormatBC1_RGBA_sRGB(131),
  MTLPixelFormatBC2_RGBA(132),
  MTLPixelFormatBC2_RGBA_sRGB(133),
  MTLPixelFormatBC3_RGBA(134),
  MTLPixelFormatBC3_RGBA_sRGB(135),
  MTLPixelFormatBC4_RUnorm(140),
  MTLPixelFormatBC4_RSnorm(141),
  MTLPixelFormatBC5_RGUnorm(142),
  MTLPixelFormatBC5_RGSnorm(143),
  MTLPixelFormatBC6H_RGBFloat(150),
  MTLPixelFormatBC6H_RGBUfloat(151),
  MTLPixelFormatBC7_RGBAUnorm(152),
  MTLPixelFormatBC7_RGBAUnorm_sRGB(153),
  MTLPixelFormatPVRTC_RGB_2BPP(160),
  MTLPixelFormatPVRTC_RGB_2BPP_sRGB(161),
  MTLPixelFormatPVRTC_RGB_4BPP(162),
  MTLPixelFormatPVRTC_RGB_4BPP_sRGB(163),
  MTLPixelFormatPVRTC_RGBA_2BPP(164),
  MTLPixelFormatPVRTC_RGBA_2BPP_sRGB(165),
  MTLPixelFormatPVRTC_RGBA_4BPP(166),
  MTLPixelFormatPVRTC_RGBA_4BPP_sRGB(167),
  MTLPixelFormatEAC_R11Unorm(170),
  MTLPixelFormatEAC_R11Snorm(172),
  MTLPixelFormatEAC_RG11Unorm(174),
  MTLPixelFormatEAC_RG11Snorm(176),
  MTLPixelFormatEAC_RGBA8(178),
  MTLPixelFormatEAC_RGBA8_sRGB(179),
  MTLPixelFormatETC2_RGB8(180),
  MTLPixelFormatETC2_RGB8_sRGB(181),
  MTLPixelFormatETC2_RGB8A1(182),
  MTLPixelFormatETC2_RGB8A1_sRGB(183),
  MTLPixelFormatASTC_4x4_sRGB(186),
  MTLPixelFormatASTC_5x4_sRGB(187),
  MTLPixelFormatASTC_5x5_sRGB(188),
  MTLPixelFormatASTC_6x5_sRGB(189),
  MTLPixelFormatASTC_6x6_sRGB(190),
  MTLPixelFormatASTC_8x5_sRGB(192),
  MTLPixelFormatASTC_8x6_sRGB(193),
  MTLPixelFormatASTC_8x8_sRGB(194),
  MTLPixelFormatASTC_10x5_sRGB(195),
  MTLPixelFormatASTC_10x6_sRGB(196),
  MTLPixelFormatASTC_10x8_sRGB(197),
  MTLPixelFormatASTC_10x10_sRGB(198),
  MTLPixelFormatASTC_12x10_sRGB(199),
  MTLPixelFormatASTC_12x12_sRGB(200),
  MTLPixelFormatASTC_4x4_LDR(204),
  MTLPixelFormatASTC_5x4_LDR(205),
  MTLPixelFormatASTC_5x5_LDR(206),
  MTLPixelFormatASTC_6x5_LDR(207),
  MTLPixelFormatASTC_6x6_LDR(208),
  MTLPixelFormatASTC_8x5_LDR(210),
  MTLPixelFormatASTC_8x6_LDR(211),
  MTLPixelFormatASTC_8x8_LDR(212),
  MTLPixelFormatASTC_10x5_LDR(213),
  MTLPixelFormatASTC_10x6_LDR(214),
  MTLPixelFormatASTC_10x8_LDR(215),
  MTLPixelFormatASTC_10x10_LDR(216),
  MTLPixelFormatASTC_12x10_LDR(217),
  MTLPixelFormatASTC_12x12_LDR(218),
  MTLPixelFormatASTC_4x4_HDR(222),
  MTLPixelFormatASTC_5x4_HDR(223),
  MTLPixelFormatASTC_5x5_HDR(224),
  MTLPixelFormatASTC_6x5_HDR(225),
  MTLPixelFormatASTC_6x6_HDR(226),
  MTLPixelFormatASTC_8x5_HDR(228),
  MTLPixelFormatASTC_8x6_HDR(229),
  MTLPixelFormatASTC_8x8_HDR(230),
  MTLPixelFormatASTC_10x5_HDR(231),
  MTLPixelFormatASTC_10x6_HDR(232),
  MTLPixelFormatASTC_10x8_HDR(233),
  MTLPixelFormatASTC_10x10_HDR(234),
  MTLPixelFormatASTC_12x10_HDR(235),
  MTLPixelFormatASTC_12x12_HDR(236),
  MTLPixelFormatGBGR422(240),
  MTLPixelFormatBGRG422(241),
  MTLPixelFormatDepth16Unorm(250),
  MTLPixelFormatDepth32Float(252),
  MTLPixelFormatStencil8(253),
  MTLPixelFormatDepth24Unorm_Stencil8(255),
  MTLPixelFormatDepth32Float_Stencil8(260),
  MTLPixelFormatX32_Stencil8(261),
  MTLPixelFormatX24_Stencil8(262);

  final int value;
  const MTLPixelFormat(this.value);

  static MTLPixelFormat fromValue(int value) => switch (value) {
    0 => MTLPixelFormatInvalid,
    1 => MTLPixelFormatA8Unorm,
    10 => MTLPixelFormatR8Unorm,
    11 => MTLPixelFormatR8Unorm_sRGB,
    12 => MTLPixelFormatR8Snorm,
    13 => MTLPixelFormatR8Uint,
    14 => MTLPixelFormatR8Sint,
    20 => MTLPixelFormatR16Unorm,
    22 => MTLPixelFormatR16Snorm,
    23 => MTLPixelFormatR16Uint,
    24 => MTLPixelFormatR16Sint,
    25 => MTLPixelFormatR16Float,
    30 => MTLPixelFormatRG8Unorm,
    31 => MTLPixelFormatRG8Unorm_sRGB,
    32 => MTLPixelFormatRG8Snorm,
    33 => MTLPixelFormatRG8Uint,
    34 => MTLPixelFormatRG8Sint,
    40 => MTLPixelFormatB5G6R5Unorm,
    41 => MTLPixelFormatA1BGR5Unorm,
    42 => MTLPixelFormatABGR4Unorm,
    43 => MTLPixelFormatBGR5A1Unorm,
    53 => MTLPixelFormatR32Uint,
    54 => MTLPixelFormatR32Sint,
    55 => MTLPixelFormatR32Float,
    60 => MTLPixelFormatRG16Unorm,
    62 => MTLPixelFormatRG16Snorm,
    63 => MTLPixelFormatRG16Uint,
    64 => MTLPixelFormatRG16Sint,
    65 => MTLPixelFormatRG16Float,
    70 => MTLPixelFormatRGBA8Unorm,
    71 => MTLPixelFormatRGBA8Unorm_sRGB,
    72 => MTLPixelFormatRGBA8Snorm,
    73 => MTLPixelFormatRGBA8Uint,
    74 => MTLPixelFormatRGBA8Sint,
    80 => MTLPixelFormatBGRA8Unorm,
    81 => MTLPixelFormatBGRA8Unorm_sRGB,
    90 => MTLPixelFormatRGB10A2Unorm,
    91 => MTLPixelFormatRGB10A2Uint,
    92 => MTLPixelFormatRG11B10Float,
    93 => MTLPixelFormatRGB9E5Float,
    94 => MTLPixelFormatBGR10A2Unorm,
    554 => MTLPixelFormatBGR10_XR,
    555 => MTLPixelFormatBGR10_XR_sRGB,
    103 => MTLPixelFormatRG32Uint,
    104 => MTLPixelFormatRG32Sint,
    105 => MTLPixelFormatRG32Float,
    110 => MTLPixelFormatRGBA16Unorm,
    112 => MTLPixelFormatRGBA16Snorm,
    113 => MTLPixelFormatRGBA16Uint,
    114 => MTLPixelFormatRGBA16Sint,
    115 => MTLPixelFormatRGBA16Float,
    552 => MTLPixelFormatBGRA10_XR,
    553 => MTLPixelFormatBGRA10_XR_sRGB,
    123 => MTLPixelFormatRGBA32Uint,
    124 => MTLPixelFormatRGBA32Sint,
    125 => MTLPixelFormatRGBA32Float,
    130 => MTLPixelFormatBC1_RGBA,
    131 => MTLPixelFormatBC1_RGBA_sRGB,
    132 => MTLPixelFormatBC2_RGBA,
    133 => MTLPixelFormatBC2_RGBA_sRGB,
    134 => MTLPixelFormatBC3_RGBA,
    135 => MTLPixelFormatBC3_RGBA_sRGB,
    140 => MTLPixelFormatBC4_RUnorm,
    141 => MTLPixelFormatBC4_RSnorm,
    142 => MTLPixelFormatBC5_RGUnorm,
    143 => MTLPixelFormatBC5_RGSnorm,
    150 => MTLPixelFormatBC6H_RGBFloat,
    151 => MTLPixelFormatBC6H_RGBUfloat,
    152 => MTLPixelFormatBC7_RGBAUnorm,
    153 => MTLPixelFormatBC7_RGBAUnorm_sRGB,
    160 => MTLPixelFormatPVRTC_RGB_2BPP,
    161 => MTLPixelFormatPVRTC_RGB_2BPP_sRGB,
    162 => MTLPixelFormatPVRTC_RGB_4BPP,
    163 => MTLPixelFormatPVRTC_RGB_4BPP_sRGB,
    164 => MTLPixelFormatPVRTC_RGBA_2BPP,
    165 => MTLPixelFormatPVRTC_RGBA_2BPP_sRGB,
    166 => MTLPixelFormatPVRTC_RGBA_4BPP,
    167 => MTLPixelFormatPVRTC_RGBA_4BPP_sRGB,
    170 => MTLPixelFormatEAC_R11Unorm,
    172 => MTLPixelFormatEAC_R11Snorm,
    174 => MTLPixelFormatEAC_RG11Unorm,
    176 => MTLPixelFormatEAC_RG11Snorm,
    178 => MTLPixelFormatEAC_RGBA8,
    179 => MTLPixelFormatEAC_RGBA8_sRGB,
    180 => MTLPixelFormatETC2_RGB8,
    181 => MTLPixelFormatETC2_RGB8_sRGB,
    182 => MTLPixelFormatETC2_RGB8A1,
    183 => MTLPixelFormatETC2_RGB8A1_sRGB,
    186 => MTLPixelFormatASTC_4x4_sRGB,
    187 => MTLPixelFormatASTC_5x4_sRGB,
    188 => MTLPixelFormatASTC_5x5_sRGB,
    189 => MTLPixelFormatASTC_6x5_sRGB,
    190 => MTLPixelFormatASTC_6x6_sRGB,
    192 => MTLPixelFormatASTC_8x5_sRGB,
    193 => MTLPixelFormatASTC_8x6_sRGB,
    194 => MTLPixelFormatASTC_8x8_sRGB,
    195 => MTLPixelFormatASTC_10x5_sRGB,
    196 => MTLPixelFormatASTC_10x6_sRGB,
    197 => MTLPixelFormatASTC_10x8_sRGB,
    198 => MTLPixelFormatASTC_10x10_sRGB,
    199 => MTLPixelFormatASTC_12x10_sRGB,
    200 => MTLPixelFormatASTC_12x12_sRGB,
    204 => MTLPixelFormatASTC_4x4_LDR,
    205 => MTLPixelFormatASTC_5x4_LDR,
    206 => MTLPixelFormatASTC_5x5_LDR,
    207 => MTLPixelFormatASTC_6x5_LDR,
    208 => MTLPixelFormatASTC_6x6_LDR,
    210 => MTLPixelFormatASTC_8x5_LDR,
    211 => MTLPixelFormatASTC_8x6_LDR,
    212 => MTLPixelFormatASTC_8x8_LDR,
    213 => MTLPixelFormatASTC_10x5_LDR,
    214 => MTLPixelFormatASTC_10x6_LDR,
    215 => MTLPixelFormatASTC_10x8_LDR,
    216 => MTLPixelFormatASTC_10x10_LDR,
    217 => MTLPixelFormatASTC_12x10_LDR,
    218 => MTLPixelFormatASTC_12x12_LDR,
    222 => MTLPixelFormatASTC_4x4_HDR,
    223 => MTLPixelFormatASTC_5x4_HDR,
    224 => MTLPixelFormatASTC_5x5_HDR,
    225 => MTLPixelFormatASTC_6x5_HDR,
    226 => MTLPixelFormatASTC_6x6_HDR,
    228 => MTLPixelFormatASTC_8x5_HDR,
    229 => MTLPixelFormatASTC_8x6_HDR,
    230 => MTLPixelFormatASTC_8x8_HDR,
    231 => MTLPixelFormatASTC_10x5_HDR,
    232 => MTLPixelFormatASTC_10x6_HDR,
    233 => MTLPixelFormatASTC_10x8_HDR,
    234 => MTLPixelFormatASTC_10x10_HDR,
    235 => MTLPixelFormatASTC_12x10_HDR,
    236 => MTLPixelFormatASTC_12x12_HDR,
    240 => MTLPixelFormatGBGR422,
    241 => MTLPixelFormatBGRG422,
    250 => MTLPixelFormatDepth16Unorm,
    252 => MTLPixelFormatDepth32Float,
    253 => MTLPixelFormatStencil8,
    255 => MTLPixelFormatDepth24Unorm_Stencil8,
    260 => MTLPixelFormatDepth32Float_Stencil8,
    261 => MTLPixelFormatX32_Stencil8,
    262 => MTLPixelFormatX24_Stencil8,
    _ => throw ArgumentError('Unknown value for MTLPixelFormat: $value'),
  };
}

final class opaqueCMFormatDescription extends ffi.Opaque {}

final class opaqueCMSampleBuffer extends ffi.Opaque {}

sealed class AVAssetReferenceRestrictions {
  static const AVAssetReferenceRestrictionForbidNone = 0;
  static const AVAssetReferenceRestrictionForbidRemoteReferenceToLocal = 1;
  static const AVAssetReferenceRestrictionForbidLocalReferenceToRemote = 2;
  static const AVAssetReferenceRestrictionForbidCrossSiteReference = 4;
  static const AVAssetReferenceRestrictionForbidLocalReferenceToLocal = 8;
  static const AVAssetReferenceRestrictionForbidAll = 65535;
  static const AVAssetReferenceRestrictionDefaultPolicy = 2;
}

sealed class AVAudioSpatializationFormats {
  static const AVAudioSpatializationFormatNone = 0;
  static const AVAudioSpatializationFormatMonoAndStereo = 3;
  static const AVAudioSpatializationFormatMultichannel = 4;
  static const AVAudioSpatializationFormatMonoStereoAndMultichannel = 7;
}

final class CMTimeRange extends ffi.Struct {
  external CMTime start;

  external CMTime duration;
}

final class CMTimeMapping extends ffi.Struct {
  external CMTimeRange source;

  external CMTimeRange target;
}

final class AVPixelAspectRatio extends ffi.Struct {
  @ffi.Long()
  external int horizontalSpacing;

  @ffi.Long()
  external int verticalSpacing;
}

final class AVEdgeWidths extends ffi.Struct {
  @ffi.Double()
  external double left;

  @ffi.Double()
  external double top;

  @ffi.Double()
  external double right;

  @ffi.Double()
  external double bottom;
}

final class OpaqueCMTagCollection extends ffi.Opaque {}

final class OpaqueCMTaggedBufferGroup extends ffi.Opaque {}

/// Construction methods for `objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)>`.
abstract final class ObjCBlock_CGRect_ffiInt_CGRect {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<objc.CGRect Function(ffi.Int arg0, objc.CGRect arg1)>
    >
    ptr,
  ) => objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)>
  fromFunction(
    objc.CGRect Function(int, objc.CGRect) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)>(
    objc.newClosureBlock(
      _closureCallable,
      (int arg0, objc.CGRect arg1) => fn(arg0, arg1),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  static objc.CGRect _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    int arg0,
    objc.CGRect arg1,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<objc.CGRect Function(ffi.Int arg0, objc.CGRect arg1)>
      >()
      .asFunction<objc.CGRect Function(int, objc.CGRect)>()(arg0, arg1);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            objc.CGRect Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Int,
              objc.CGRect,
            )
          >(_fnPtrTrampoline)
          .cast();
  static objc.CGRect _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    int arg0,
    objc.CGRect arg1,
  ) => (objc.getBlockClosure(block) as objc.CGRect Function(int, objc.CGRect))(
    arg0,
    arg1,
  );
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            objc.CGRect Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Int,
              objc.CGRect,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)>`.
extension ObjCBlock_CGRect_ffiInt_CGRect$CallExtension
    on objc.ObjCBlock<objc.CGRect Function(ffi.Int, objc.CGRect)> {
  objc.CGRect call(int arg0, objc.CGRect arg1) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          objc.CGRect Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Int arg0,
            objc.CGRect arg1,
          )
        >
      >()
      .asFunction<
        objc.CGRect Function(ffi.Pointer<objc.ObjCBlockImpl>, int, objc.CGRect)
      >()(ref.pointer, arg0, arg1);
}

enum CIRenderDestinationAlphaMode {
  CIRenderDestinationAlphaNone(0),
  CIRenderDestinationAlphaPremultiplied(1),
  CIRenderDestinationAlphaUnpremultiplied(2);

  final int value;
  const CIRenderDestinationAlphaMode(this.value);

  static CIRenderDestinationAlphaMode fromValue(int value) => switch (value) {
    0 => CIRenderDestinationAlphaNone,
    1 => CIRenderDestinationAlphaPremultiplied,
    2 => CIRenderDestinationAlphaUnpremultiplied,
    _ => throw ArgumentError(
      'Unknown value for CIRenderDestinationAlphaMode: $value',
    ),
  };
}

final class CATransform3D extends ffi.Struct {
  @ffi.Double()
  external double m11;

  @ffi.Double()
  external double m12;

  @ffi.Double()
  external double m13;

  @ffi.Double()
  external double m14;

  @ffi.Double()
  external double m21;

  @ffi.Double()
  external double m22;

  @ffi.Double()
  external double m23;

  @ffi.Double()
  external double m24;

  @ffi.Double()
  external double m31;

  @ffi.Double()
  external double m32;

  @ffi.Double()
  external double m33;

  @ffi.Double()
  external double m34;

  @ffi.Double()
  external double m41;

  @ffi.Double()
  external double m42;

  @ffi.Double()
  external double m43;

  @ffi.Double()
  external double m44;
}

sealed class CAAutoresizingMask {
  static const kCALayerNotSizable = 0;
  static const kCALayerMinXMargin = 1;
  static const kCALayerWidthSizable = 2;
  static const kCALayerMaxXMargin = 4;
  static const kCALayerMinYMargin = 8;
  static const kCALayerHeightSizable = 16;
  static const kCALayerMaxYMargin = 32;
}

sealed class CAEdgeAntialiasingMask {
  static const kCALayerLeftEdge = 1;
  static const kCALayerRightEdge = 2;
  static const kCALayerBottomEdge = 4;
  static const kCALayerTopEdge = 8;
}

sealed class CACornerMask {
  static const kCALayerMinXMinYCorner = 1;
  static const kCALayerMaxXMinYCorner = 2;
  static const kCALayerMinXMaxYCorner = 4;
  static const kCALayerMaxXMaxYCorner = 8;
}

final class CAFrameRateRange extends ffi.Struct {
  @ffi.Float()
  external double minimum;

  @ffi.Float()
  external double maximum;

  @ffi.Float()
  external double preferred;
}

enum CAConstraintAttribute {
  kCAConstraintMinX(0),
  kCAConstraintMidX(1),
  kCAConstraintMaxX(2),
  kCAConstraintWidth(3),
  kCAConstraintMinY(4),
  kCAConstraintMidY(5),
  kCAConstraintMaxY(6),
  kCAConstraintHeight(7);

  final int value;
  const CAConstraintAttribute(this.value);

  static CAConstraintAttribute fromValue(int value) => switch (value) {
    0 => kCAConstraintMinX,
    1 => kCAConstraintMidX,
    2 => kCAConstraintMaxX,
    3 => kCAConstraintWidth,
    4 => kCAConstraintMinY,
    5 => kCAConstraintMidY,
    6 => kCAConstraintMaxY,
    7 => kCAConstraintHeight,
    _ => throw ArgumentError('Unknown value for CAConstraintAttribute: $value'),
  };
}

final class OpaqueCMClock extends ffi.Opaque {}

final class OpaqueCMTimebase extends ffi.Opaque {}

enum AVPlayerStatus {
  AVPlayerStatusUnknown(0),
  AVPlayerStatusReadyToPlay(1),
  AVPlayerStatusFailed(2);

  final int value;
  const AVPlayerStatus(this.value);

  static AVPlayerStatus fromValue(int value) => switch (value) {
    0 => AVPlayerStatusUnknown,
    1 => AVPlayerStatusReadyToPlay,
    2 => AVPlayerStatusFailed,
    _ => throw ArgumentError('Unknown value for AVPlayerStatus: $value'),
  };
}

/// WARNING: AVPlayer is a stub. To generate bindings for this class, include
/// AVPlayer in your config's objc-interfaces list.
///
/// AVPlayer
extension type AVPlayer._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [AVPlayer] that points to the same underlying object as [other].
  AVPlayer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'AVPlayer',
      iOS: (false, (4, 0, 0)),
      macOS: (false, (10, 7, 0)),
    );
  }

  /// Constructs a [AVPlayer] that wraps the given raw object pointer.
  AVPlayer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'AVPlayer',
      iOS: (false, (4, 0, 0)),
      macOS: (false, (10, 7, 0)),
    );
  }
}

enum AVPlayerTimeControlStatus {
  AVPlayerTimeControlStatusPaused(0),
  AVPlayerTimeControlStatusWaitingToPlayAtSpecifiedRate(1),
  AVPlayerTimeControlStatusPlaying(2);

  final int value;
  const AVPlayerTimeControlStatus(this.value);

  static AVPlayerTimeControlStatus fromValue(int value) => switch (value) {
    0 => AVPlayerTimeControlStatusPaused,
    1 => AVPlayerTimeControlStatusWaitingToPlayAtSpecifiedRate,
    2 => AVPlayerTimeControlStatusPlaying,
    _ => throw ArgumentError(
      'Unknown value for AVPlayerTimeControlStatus: $value',
    ),
  };
}

enum AVPlayerActionAtItemEnd {
  AVPlayerActionAtItemEndAdvance(0),
  AVPlayerActionAtItemEndPause(1),
  AVPlayerActionAtItemEndNone(2);

  final int value;
  const AVPlayerActionAtItemEnd(this.value);

  static AVPlayerActionAtItemEnd fromValue(int value) => switch (value) {
    0 => AVPlayerActionAtItemEndAdvance,
    1 => AVPlayerActionAtItemEndPause,
    2 => AVPlayerActionAtItemEndNone,
    _ => throw ArgumentError(
      'Unknown value for AVPlayerActionAtItemEnd: $value',
    ),
  };
}

sealed class AVPlayerHDRMode {
  static const AVPlayerHDRModeHLG = 1;
  static const AVPlayerHDRModeHDR10 = 2;
  static const AVPlayerHDRModeDolbyVision = 4;
}

enum AVPlayerAudiovisualBackgroundPlaybackPolicy {
  AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic(1),
  AVPlayerAudiovisualBackgroundPlaybackPolicyPauses(2),
  AVPlayerAudiovisualBackgroundPlaybackPolicyContinuesIfPossible(3);

  final int value;
  const AVPlayerAudiovisualBackgroundPlaybackPolicy(this.value);

  static AVPlayerAudiovisualBackgroundPlaybackPolicy fromValue(
    int value,
  ) => switch (value) {
    1 => AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic,
    2 => AVPlayerAudiovisualBackgroundPlaybackPolicyPauses,
    3 => AVPlayerAudiovisualBackgroundPlaybackPolicyContinuesIfPossible,
    _ => throw ArgumentError(
      'Unknown value for AVPlayerAudiovisualBackgroundPlaybackPolicy: $value',
    ),
  };
}

enum AVPlayerItemStatus {
  AVPlayerItemStatusUnknown(0),
  AVPlayerItemStatusReadyToPlay(1),
  AVPlayerItemStatusFailed(2);

  final int value;
  const AVPlayerItemStatus(this.value);

  static AVPlayerItemStatus fromValue(int value) => switch (value) {
    0 => AVPlayerItemStatusUnknown,
    1 => AVPlayerItemStatusReadyToPlay,
    2 => AVPlayerItemStatusFailed,
    _ => throw ArgumentError('Unknown value for AVPlayerItemStatus: $value'),
  };
}

sealed class AVVariantPreferences {
  static const AVVariantPreferenceNone = 0;
  static const AVVariantPreferenceScalabilityToLosslessAudio = 1;
}

enum AVContentAuthorizationStatus {
  AVContentAuthorizationUnknown(0),
  AVContentAuthorizationCompleted(1),
  AVContentAuthorizationCancelled(2),
  AVContentAuthorizationTimedOut(3),
  AVContentAuthorizationBusy(4),
  AVContentAuthorizationNotAvailable(5),
  AVContentAuthorizationNotPossible(6);

  final int value;
  const AVContentAuthorizationStatus(this.value);

  static AVContentAuthorizationStatus fromValue(int value) => switch (value) {
    0 => AVContentAuthorizationUnknown,
    1 => AVContentAuthorizationCompleted,
    2 => AVContentAuthorizationCancelled,
    3 => AVContentAuthorizationTimedOut,
    4 => AVContentAuthorizationBusy,
    5 => AVContentAuthorizationNotAvailable,
    6 => AVContentAuthorizationNotPossible,
    _ => throw ArgumentError(
      'Unknown value for AVContentAuthorizationStatus: $value',
    ),
  };
}

sealed class AVPlayerInterstitialEventRestrictions {
  static const AVPlayerInterstitialEventRestrictionNone = 0;
  static const AVPlayerInterstitialEventRestrictionConstrainsSeekingForwardInPrimaryContent =
      1;
  static const AVPlayerInterstitialEventRestrictionRequiresPlaybackAtPreferredRateForAdvancement =
      4;
  static const AVPlayerInterstitialEventRestrictionDefaultPolicy = 0;
}

enum AVPlayerInterstitialEventTimelineOccupancy {
  AVPlayerInterstitialEventTimelineOccupancySinglePoint(0),
  AVPlayerInterstitialEventTimelineOccupancyFill(1);

  final int value;
  const AVPlayerInterstitialEventTimelineOccupancy(this.value);

  static AVPlayerInterstitialEventTimelineOccupancy fromValue(
    int value,
  ) => switch (value) {
    0 => AVPlayerInterstitialEventTimelineOccupancySinglePoint,
    1 => AVPlayerInterstitialEventTimelineOccupancyFill,
    _ => throw ArgumentError(
      'Unknown value for AVPlayerInterstitialEventTimelineOccupancy: $value',
    ),
  };
}

enum AVPlayerItemSegmentType {
  AVPlayerItemSegmentTypePrimary(0),
  AVPlayerItemSegmentTypeInterstitial(1);

  final int value;
  const AVPlayerItemSegmentType(this.value);

  static AVPlayerItemSegmentType fromValue(int value) => switch (value) {
    0 => AVPlayerItemSegmentTypePrimary,
    1 => AVPlayerItemSegmentTypeInterstitial,
    _ => throw ArgumentError(
      'Unknown value for AVPlayerItemSegmentType: $value',
    ),
  };
}

final class AVSampleCursorSyncInfo extends ffi.Struct {
  @ffi.Bool()
  external bool sampleIsFullSync;

  @ffi.Bool()
  external bool sampleIsPartialSync;

  @ffi.Bool()
  external bool sampleIsDroppable;
}

final class AVSampleCursorDependencyInfo extends ffi.Struct {
  @ffi.Bool()
  external bool sampleIndicatesWhetherItHasDependentSamples;

  @ffi.Bool()
  external bool sampleHasDependentSamples;

  @ffi.Bool()
  external bool sampleIndicatesWhetherItDependsOnOthers;

  @ffi.Bool()
  external bool sampleDependsOnOthers;

  @ffi.Bool()
  external bool sampleIndicatesWhetherItHasRedundantCoding;

  @ffi.Bool()
  external bool sampleHasRedundantCoding;
}

final class AVSampleCursorAudioDependencyInfo extends ffi.Struct {
  @ffi.Bool()
  external bool audioSampleIsIndependentlyDecodable;

  @ffi.Long()
  external int audioSamplePacketRefreshCount;
}

final class AVSampleCursorStorageRange extends ffi.Struct {
  @ffi.Int64()
  external int offset;

  @ffi.Int64()
  external int length;
}

final class AVSampleCursorChunkInfo extends ffi.Struct {
  @ffi.Int64()
  external int chunkSampleCount;

  @ffi.Bool()
  external bool chunkHasUniformSampleSizes;

  @ffi.Bool()
  external bool chunkHasUniformSampleDurations;

  @ffi.Bool()
  external bool chunkHasUniformFormatDescriptions;
}

enum AVDepthDataQuality {
  AVDepthDataQualityLow(0),
  AVDepthDataQualityHigh(1);

  final int value;
  const AVDepthDataQuality(this.value);

  static AVDepthDataQuality fromValue(int value) => switch (value) {
    0 => AVDepthDataQualityLow,
    1 => AVDepthDataQualityHigh,
    _ => throw ArgumentError('Unknown value for AVDepthDataQuality: $value'),
  };
}

enum AVDepthDataAccuracy {
  AVDepthDataAccuracyRelative(0),
  AVDepthDataAccuracyAbsolute(1);

  final int value;
  const AVDepthDataAccuracy(this.value);

  static AVDepthDataAccuracy fromValue(int value) => switch (value) {
    0 => AVDepthDataAccuracyRelative,
    1 => AVDepthDataAccuracyAbsolute,
    _ => throw ArgumentError('Unknown value for AVDepthDataAccuracy: $value'),
  };
}

late final _class_FVPVideoPlayer = objc.getClass("FVPVideoPlayer");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_player = objc.registerName("player");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_disposed = objc.registerName("disposed");
final _objc_msgSend_91o635 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_isLooping = objc.registerName("isLooping");
late final _sel_setIsLooping_ = objc.registerName("setIsLooping:");
final _objc_msgSend_1s56lr9 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Bool,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        bool,
      )
    >();
late final _sel_position = objc.registerName("position");
final _objc_msgSend_pysgoz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Int64 Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_eventListener = objc.registerName("eventListener");
late final _sel_setEventListener_ = objc.registerName("setEventListener:");
final _objc_msgSend_xtuoz7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();

/// Construction methods for `objc.ObjCBlock<ffi.Void Function()>`.
abstract final class ObjCBlock_ffiVoid {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Void Function()> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Void Function()>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Void Function()> fromFunctionPointer(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> ptr,
  ) => objc.ObjCBlock<ffi.Void Function()>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function()> fromFunction(
    void Function() fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Void Function()>(
    objc.newClosureBlock(_closureCallable, () => fn(), keepIsolateAlive),
    retain: false,
    release: true,
  );

  /// Creates a listener block from a Dart function.
  ///
  /// This is based on FFI's NativeCallable.listener, and has the same
  /// capabilities and limitations. This block can be invoked from any thread,
  /// but only supports void functions, and is not run synchronously. See
  /// NativeCallable.listener for more details.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function()> listener(
    void Function() fn, {
    bool keepIsolateAlive = true,
  }) {
    final raw = objc.newClosureBlock(
      _listenerCallable.nativeFunction.cast(),
      () => fn(),
      keepIsolateAlive,
    );
    final wrapper = _NativeLibrary_wrapListenerBlock_1pl9qdv(raw);
    objc.objectRelease(raw.cast());
    return objc.ObjCBlock<ffi.Void Function()>(
      wrapper,
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<ffi.Void Function()> blocking(
    void Function() fn, {
    bool keepIsolateAlive = true,
  }) {
    final raw = objc.newClosureBlock(
      _blockingCallable.nativeFunction.cast(),
      () => fn(),
      keepIsolateAlive,
    );
    final rawListener = objc.newClosureBlock(
      _blockingListenerCallable.nativeFunction.cast(),
      () => fn(),
      keepIsolateAlive,
    );
    final wrapper = _NativeLibrary_wrapBlockingBlock_1pl9qdv(
      raw,
      rawListener,
      objc.objCContext,
    );
    objc.objectRelease(raw.cast());
    objc.objectRelease(rawListener.cast());
    return objc.ObjCBlock<ffi.Void Function()>(
      wrapper,
      retain: false,
      release: true,
    );
  }

  static void _listenerTrampoline(ffi.Pointer<objc.ObjCBlockImpl> block) {
    (objc.getBlockClosure(block) as void Function())();
    objc.objectRelease(block.cast());
  }

  static ffi.NativeCallable<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>)>
  _listenerCallable =
      ffi.NativeCallable<
          ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>)
        >.listener(_listenerTrampoline)
        ..keepIsolateAlive = false;
  static void _blockingTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> waiter,
  ) {
    try {
      (objc.getBlockClosure(block) as void Function())();
    } catch (e) {
    } finally {
      objc.signalWaiter(waiter);
      objc.objectRelease(block.cast());
    }
  }

  static ffi.NativeCallable<
    ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Pointer<ffi.Void>)
  >
  _blockingCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
          )
        >.isolateLocal(_blockingTrampoline)
        ..keepIsolateAlive = false;
  static ffi.NativeCallable<
    ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Pointer<ffi.Void>)
  >
  _blockingListenerCallable =
      ffi.NativeCallable<
          ffi.Void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
          )
        >.listener(_blockingTrampoline)
        ..keepIsolateAlive = false;
  static void _fnPtrTrampoline(ffi.Pointer<objc.ObjCBlockImpl> block) => block
      .ref
      .target
      .cast<ffi.NativeFunction<ffi.Void Function()>>()
      .asFunction<void Function()>()();
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>)
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(ffi.Pointer<objc.ObjCBlockImpl> block) =>
      (objc.getBlockClosure(block) as void Function())();
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>)
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function()>`.
extension ObjCBlock_ffiVoid$CallExtension
    on objc.ObjCBlock<ffi.Void Function()> {
  void call() =>
      ref.pointer.ref.invoke
          .cast<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl> block)
            >
          >()
          .asFunction<void Function(ffi.Pointer<objc.ObjCBlockImpl>)>()(
        ref.pointer,
      );
}

late final _sel_onDisposed = objc.registerName("onDisposed");
final _objc_msgSend_uwvaik = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCBlockImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCBlockImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setOnDisposed_ = objc.registerName("setOnDisposed:");
final _objc_msgSend_f167m6 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();
late final _sel_play = objc.registerName("play");
final _objc_msgSend_1pl9qdv = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_pause = objc.registerName("pause");
late final _sel_seekTo_completion_ = objc.registerName("seekTo:completion:");
final _objc_msgSend_1i0cxyc = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Int64,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();
late final _sel_setLooping_ = objc.registerName("setLooping:");
late final _sel_setVolume_ = objc.registerName("setVolume:");
final _objc_msgSend_hwm8nu = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Double,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        double,
      )
    >();
late final _sel_setPlaybackSpeed_ = objc.registerName("setPlaybackSpeed:");
late final _sel_dispose = objc.registerName("dispose");
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_init = objc.registerName("init");
late final _sel_new = objc.registerName("new");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");

/// FVPVideoPlayer manages video playback using AVPlayer.
/// It provides methods for controlling playback, adjusting volume, and handling seeking.
/// This class contains all functionalities needed to manage video playback in platform views and is
/// typically used alongside FVPNativeVideoViewFactory. If you need to display a video using a
/// texture, use FVPTextureBasedVideoPlayer instead.
extension type FVPVideoPlayer._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [FVPVideoPlayer] that points to the same underlying object as [other].
  FVPVideoPlayer.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [FVPVideoPlayer] that wraps the given raw object pointer.
  FVPVideoPlayer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [FVPVideoPlayer].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_FVPVideoPlayer,
  );

  /// alloc
  static FVPVideoPlayer alloc() {
    final $ret = _objc_msgSend_151sglz(_class_FVPVideoPlayer, _sel_alloc);
    return FVPVideoPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static FVPVideoPlayer allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_FVPVideoPlayer,
      _sel_allocWithZone_,
      zone,
    );
    return FVPVideoPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static FVPVideoPlayer new$() {
    final $ret = _objc_msgSend_151sglz(_class_FVPVideoPlayer, _sel_new);
    return FVPVideoPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of FVPVideoPlayer constructed with the default `new` method.
  FVPVideoPlayer() : this.as(new$().object$);
}

extension FVPVideoPlayer$Methods on FVPVideoPlayer {
  /// dispose
  void dispose() {
    _objc_msgSend_1pl9qdv(object$.ref.pointer, _sel_dispose);
  }

  /// Indicates whether the video player has been disposed.
  bool get disposed {
    return _objc_msgSend_91o635(object$.ref.pointer, _sel_disposed);
  }

  /// The event listener to report video events to.
  objc.NSObject? get eventListener {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_eventListener);
    return $ret.address == 0
        ? null
        : objc.NSObject.fromPointer($ret, retain: true, release: true);
  }

  /// init
  FVPVideoPlayer init() {
    objc.checkOsVersionInternal(
      'FVPVideoPlayer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return FVPVideoPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// Indicates whether the video player is set to loop.
  bool get isLooping {
    return _objc_msgSend_91o635(object$.ref.pointer, _sel_isLooping);
  }

  /// A block that will be called when dispose is called.
  objc.ObjCBlock<ffi.Void Function()>? get onDisposed {
    final $ret = _objc_msgSend_uwvaik(object$.ref.pointer, _sel_onDisposed);
    return $ret.address == 0
        ? null
        : ObjCBlock_ffiVoid.fromPointer($ret, retain: true, release: true);
  }

  /// pause
  void pause() {
    _objc_msgSend_1pl9qdv(object$.ref.pointer, _sel_pause);
  }

  /// play
  void play() {
    _objc_msgSend_1pl9qdv(object$.ref.pointer, _sel_play);
  }

  /// The AVPlayer instance used for video playback.
  AVPlayer get player {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_player);
    return AVPlayer.fromPointer($ret, retain: true, release: true);
  }

  /// The current playback position of the video, in milliseconds.
  int get position {
    return _objc_msgSend_pysgoz(object$.ref.pointer, _sel_position);
  }

  /// seekTo:completion:
  void seekTo(
    int position, {
    required objc.ObjCBlock<ffi.Void Function()> completion,
  }) {
    _objc_msgSend_1i0cxyc(
      object$.ref.pointer,
      _sel_seekTo_completion_,
      position,
      completion.ref.pointer,
    );
  }

  /// The event listener to report video events to.
  set eventListener(objc.NSObject? value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setEventListener_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  /// Indicates whether the video player is set to loop.
  set isLooping(bool value) {
    _objc_msgSend_1s56lr9(object$.ref.pointer, _sel_setIsLooping_, value);
  }

  /// setLooping:
  void setLooping(bool looping) {
    _objc_msgSend_1s56lr9(object$.ref.pointer, _sel_setLooping_, looping);
  }

  /// A block that will be called when dispose is called.
  set onDisposed(objc.ObjCBlock<ffi.Void Function()>? value) {
    _objc_msgSend_f167m6(
      object$.ref.pointer,
      _sel_setOnDisposed_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  /// setPlaybackSpeed:
  void setPlaybackSpeed(double speed) {
    _objc_msgSend_hwm8nu(object$.ref.pointer, _sel_setPlaybackSpeed_, speed);
  }

  /// setVolume:
  void setVolume(double volume) {
    _objc_msgSend_hwm8nu(object$.ref.pointer, _sel_setVolume_, volume);
  }
}
