name: pr_inspector
description: A command line tool to inspect GitHub PRs.
version: 0.0.1
environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  ansicolor: ^2.0.3
  args: ^2.5.0
  collection: ^1.19.1
  http: ^1.2.2

dev_dependencies:
  test: ^1.16.0
